name: test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.8", "luajit", "luajit-2.0", "luajit-2.1", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        machineTag: ["ubuntu-latest", "macos-latest", "windows-latest"]
        exclude:
          - luaVersion: "luajit-2.0"
            machineTag: "macos-latest"
          - luaVersion: "luajit-2.0.5"
            machineTag: "macos-latest"
          - luaVersion: "luajit-2.0.5"
            machineTag: "windows-latest"
          - luaVersion: "luajit-2.1.0-beta3"
            machineTag: "windows-latest"

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build Lua
      uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}
        buildCache: false

    - name: Test Lua
      run: lua -e "print('hi from lua')"

  test-cache:
    needs: test

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.8", "luajit", "luajit-2.0", "luajit-2.1", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        machineTag: ["ubuntu-latest", "macos-latest", "windows-latest"]
        exclude:
          - luaVersion: "luajit-2.0"
            machineTag: "macos-latest"
          - luaVersion: "luajit-2.0.5"
            machineTag: "macos-latest"
          - luaVersion: "luajit-2.0.5"
            machineTag: "windows-latest"
          - luaVersion: "luajit-2.1.0-beta3"
            machineTag: "windows-latest"

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Get Lua from cache
      uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Test Lua
      run: lua -e "print('hi from lua')"
